repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -  id: format-ruby-files
       name: Format *.rb files
       entry: rubyfmt -i Formula/*.rb
       language: system
